### ISSUE TITLE
v-model not update in input

### ISSUE THREAD

**Issue by thiagoanselmo** [phoenixwong/vue2-timepicker#50] opened 2018-03-28 22:53 UTC
Clicking the two way databind button does not update the <vue-timepicker> to 11

```
// v-for
<vue-timepicker v-model="....startPerild1"></vue-timepicker>
<vue-timepicker v-model="....startPerild2"></vue-timepicker>
<vue-timepicker v-model="....startPerild3"></vue-timepicker>

<button @click="setSelectDayAccess"></button>
```
```
data () {
 return {
       itemsTableDayAccess: [
           { startPerild1: {'HH': '10', 'mm': '50'},
           { startPerild2: {'HH': '', 'mm': ''},
           { startPerild3: {'HH': '', 'mm': ''}
      ]
 }
}
```
```
 setSelectDayAccess () {
      this.itemsTableDayAccess = this.itemsTableDayAccess.map(item => {
        item.startPerild1.HH = '11'
        return item
      })
    },

**Comment by bazuzu931** [comment] 2019-02-03 18:47
same problem

**Comment by rsanjeeban** [comment] 2019-07-04 05:00
Same issue

**Comment by phoenixwong** [comment] 2019-08-07 14:57
Duplicate of #27

**Closed by phoenixwong** 2019-08-07 14:57 UTC

**Comment by phoenixwong** [comment] 2019-08-10 12:13
Done more fixes in the [latest release](https://github.com/phoenixwong/vue2-timepicker/releases/latest) (v0.2.2)

```javascript
// Data
data () {
  return {
    itemsTableDayAccess: [
      {
        startPerild1: {'HH': '10', 'mm': '50'},
        startPerild2: {'HH': '', 'mm': ''},
        startPerild3: {'HH': '', 'mm': ''}
      },
      {
        startPerild1: {'HH': '03', 'mm': '10'},
        startPerild2: {'HH': '', 'mm': ''},
        startPerild3: {'HH': '', 'mm': ''}
      }
    ],
  }
}
```

```html
<!-- v-for HTML -->
<div v-for="(tableDay, tdIdx) in itemsTableDayAccess" :key="tdIdx">
  <p>
    <b>`itemsTableDayAccess` group {{tdIdx + 1}}:</b>
  </p>
  <p>
    <vue-timepicker v-model="tableDay.startPerild1"></vue-timepicker>
    <vue-timepicker v-model="tableDay.startPerild2"></vue-timepicker>
    <vue-timepicker v-model="tableDay.startPerild3"></vue-timepicker>
  </p>
</div>
```

```javascript
methods: {
  setSelectDayAccess () {
    // Before
    // this.itemsTableDayAccess = this.itemsTableDayAccess.map(item => {
    //   item.startPerild1.HH = '11'
    //   return item
    // })

    // Suggestion
    this.itemsTableDayAccess.map((item, index) => {
      this.$set(this.itemsTableDayAccess[index].startPerild1, 'HH', '11')
    })
  }
}
```

Working [jsFiddle sample](https://jsfiddle.net/phoenixwong/mqypzwho/).

FYI, rather than using the Array `.map` to update the whole variable. I'd recommend `this.$set` instead. It is more reliable and efficient in data reactivity. [Vue Docs](https://vuejs.org/v2/guide/reactivity.html)
