### ISSUE TITLE
Dropdown doesn't close

### ISSUE THREAD

**Issue by piterio** [phoenixwong/vue2-timepicker#109] opened 2020-05-14 12:43 UTC
Hi, I'm trying to use vue2-timepicker in a project but somehow when I made a click outside the input (the component creates a time-picker-overlay layer) the dropdown try to close (calls close method) but inmediatly calls open again and it never closes. I have to click down and 1 second later (more or less) when I stop clicking then dropdown closes. 

Any thoughts about what is happening? 

Thank you in advance

**Comment by phoenixwong** [comment] 2020-05-14 15:38
Hi, can you reproduce the issue with JSFiddle or CodePen? It's hard to determine the cause without a workable case.

FYI, here is a [Vue2 Timepicker v1.0.8 Demo Base](https://jsfiddle.net/phoenixwong/fxbgu9Lz/) on JSFiddle. Please feel free to fork it as a scaffold.

**Comment by phoenixwong** [comment] 2020-06-14 15:25
I am closing this for lacking information. Please feel free to reopen it with a working demo.

**Closed by phoenixwong** 2020-06-14 15:25 UTC
Labels: :information_source: info needed

**Comment by depsimon** [comment] 2020-09-15 14:44
I had the same issue, hard to reproduce in a fresh project.
I fixed it by reseting the `.time-picker-overlay` z-index.

```css
.time-picker-overlay {
    z-index: -1 !important;
}
```

**Comment by shawn-k-cissdm** [comment] 2020-10-21 19:34
@phoenixwong I encounter this same issue when i am loading a component dynamically which contains vue-timepicker. 
i.e.
in a parent component:
```
<component is="dynamicLoadedTimepickerComponent">
</component>
```
where dynamicLoadedTimepickerComponent is a SFC containing `<vue-timepicker>`

**Comment by phoenixwong** [comment] 2020-10-25 12:00
Hi @shawn-k-cissdm,

Did you try the resolution provided by [depsimon](https://github.com/phoenixwong/vue2-timepicker/issues/109#issuecomment-692763093) and/or [MadhuPolu](https://github.com/phoenixwong/vue2-timepicker/issues/126#issuecomment-667677135)?

If their solution is not helping for your case, can you give more clues about the situation when an opened Vue TimePicker failed to close? Like, its parent component or itself being re-mounted/destroyed while the dropdown is still opening? Because I see you are including it within a dynamically loaded parent component.

We need more information to do further debugging. It will be even better if you can recreate the issue in JSFiddle or CodePen. FYI, here is the latest [Vue2 Timepicker Demo Base](https://jsfiddle.net/phoenixwong/p1o4m7ae/) on JSFiddle. Please feel free to fork it as a scaffold.
