### ISSUE TITLE
[New Maintainer] please see xxRockOnxx/vue2-timepicker

### ISSUE THREAD

**Issue by xxRockOnxx** [phoenixwong/vue2-timepicker#41] opened 2017-10-21 04:02 UTC
Please see my fork. I am trying to maintain this project. Thanks.

**Comment by Aksem** [comment] 2017-10-27 09:05
@xxRockOnxx i tried your fork and disabled option works well, but picker has 12 hours format independent from options.

**Comment by xxRockOnxx** [comment] 2017-10-27 13:31
please open issue on my repo.

**Comment by phoenixwong** [comment] 2019-08-07 04:59
Sorry for the long silence. Thank you, @xxRockOnxx, for lending a helping hand in the meantime! Dead repo rechanged in mid-2019 now 💡  

Duplicate of #36

**Closed by phoenixwong** 2019-08-07 04:59 UTC
